Reset `base_url` when `setTestMode()` is called
MyOnlineStore/omnipay-klarna-checkout pull request #61
Opened 2019-02-26 16:59 UTC by shopblocks

When `setTestMode()` is called the `base_url` value is likely to change. Currently the `base_url` can only be set on `initialize()` call so any changes to `testMode` after that will not update the `base_url` value.

2019-02-27 10:20 UTC, Feijs requested changes
Thanks for your contribution!

2019-02-27 10:20 UTC, Feijs commented on src/Gateway.php
> +        $this->setParameter('testMode', $testMode);
I'd use `parent::setTestMode` here, so it doesn't need to be kept in sync with any changes to the parent implementation.

2019-02-27 10:20 UTC, Feijs commented on src/Gateway.php
> +    public function setTestMode($testMode): self
This function is not covered, could you add a unit test for it? See `testInitialisationWillSetCorrectBaseUrl` as example

2019-02-27 10:20 UTC, Feijs commented on src/Gateway.php
> +        return $this;
Please add a blank line before return statements ([Symfony CS](https://symfony.com/doc/current/contributing/code/standards.html), I notice this is not defined within the package yet, I'll add it soon)

2019-02-27 10:37 UTC, digibeuk commented on src/Gateway.php
> +            $this->parameters->set('base_url', $this->getTestMode() ? self::EU_TEST_BASE_URL : self::EU_BASE_URL);
you can use an early return here, so you do not need the else

2019-02-27 14:00 UTC, shopblocks commented
Made the changes asked for

2019-02-28 11:10 UTC, Feijs commented on src/Gateway.php
> +            return $this;
No need to return self in a private function, this can just be `return` (and the final return can be dropped altogether)

2019-03-06 12:56 UTC, Feijs approved these changes

2019-03-06 12:56 UTC, merged