Allow organizations and companies to checkout
MyOnlineStore/omnipay-klarna-checkout pull request #68
Opened 2020-01-27 15:40 UTC by jannejava

Create an order with these options to allow companyies to checkout: $order['widget_options']['allowed_customer_types'] = ['person', 'organization'];

https://developers.klarna.com/api/#checkout-api-callbacks__order-validationoptions__allowed_customer_types

2020-08-18 10:05 UTC, fred-jan requested changes
Thank you for the contribution and my apologies the the delayed response :smile: 

Could you adjust the corresponding unit test as well? Will merge the change afterwards.

2020-08-26 09:51 UTC, jannejava commented
I have looked into this now, no problems writing a test. However, I cannot make the tests to run on PHP7.4. I think PHPUnit needs to be upgraded in `omnipay/tests` to be compatible with 7.4. 

```
Function ReflectionType::__toString() is deprecated

ERRORS!
Tests: 163, Assertions: 113, Errors: 94.

```

2020-09-14 14:46 UTC, fred-jan commented
Weird, PHPUnit seems to be working fine here using PHP 7.4 on your branch:
```php vendor/bin/phpunit            
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

...............................................................  63 / 163 ( 38%)
............................................................... 126 / 163 ( 77%)
.....................................                           163 / 163 (100%)

Time: 83 ms, Memory: 10.00MB

OK (163 tests, 270 assertions)
```
I did fix the failing unit tests in the process by making these changes:
```
Index: tests/Message/WidgetOptionsTest.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tests/Message/WidgetOptionsTest.php	(revision 9398bb8dafde25231e20c68c7c0b2374c6d47391)
+++ tests/Message/WidgetOptionsTest.php	(date 1600094266067)
@@ -57,6 +57,7 @@
                     'show_subtotal_detail' => true,
                     'require_validate_callback_success' => true,
                     'allow_global_billing_countries' => false,
+                    'allowed_customer_types' => 'person',
                 ],
             ],
             [
@@ -78,6 +79,7 @@
                     'show_subtotal_detail' => false,
                     'require_validate_callback_success' => false,
                     'allow_global_billing_countries' => false,
+                    'allowed_customer_types' => 'person',
                 ],
             ],
             [
@@ -99,6 +101,7 @@
                     'show_subtotal_detail' => false,
                     'require_validate_callback_success' => false,
                     'allow_global_billing_countries' => false,
+                    'allowed_customer_types' => 'person',
                 ],
             ],
         ];
Index: tests/Message/UpdateTransactionRequestTest.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tests/Message/UpdateTransactionRequestTest.php	(revision 9398bb8dafde25231e20c68c7c0b2374c6d47391)
+++ tests/Message/UpdateTransactionRequestTest.php	(date 1600094195906)
@@ -310,6 +310,7 @@
             'show_subtotal_detail' => true,
             'require_validate_callback_success' => true,
             'allow_global_billing_countries' => false,
+            'allowed_customer_types' => 'person',
         ];
 
         $this->updateTransactionRequest->initialize(
@@ -322,7 +323,7 @@
                 'gui_minimal_confirmation' => true,
                 'gui_autofocus' => false,
                 'merchant_reference1' => '12345',
-                'merchant_reference2' => 678,
+                'merchant_reference2' => '678',
                 'purchase_country' => 'DE',
             ]
         );
@@ -341,7 +342,7 @@
                 'purchase_currency' => 'EUR',
                 'gui' => ['options' => ['disable_autofocus', 'minimal_confirmation']],
                 'merchant_reference1' => '12345',
-                'merchant_reference2' => 678,
+                'merchant_reference2' => '678',
                 'options' => $widgetOptions,
             ],
             $this->updateTransactionRequest->getData()
Index: tests/Message/AuthorizeRequestTest.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tests/Message/AuthorizeRequestTest.php	(revision 9398bb8dafde25231e20c68c7c0b2374c6d47391)
+++ tests/Message/AuthorizeRequestTest.php	(date 1600094156853)
@@ -255,6 +255,7 @@
             'show_subtotal_detail' => true,
             'require_validate_callback_success' => true,
             'allow_global_billing_countries' => false,
+            'allowed_customer_types' => 'person'
         ];
 
         $this->authorizeRequest->initialize(
```

Also, can you tell me if `person` is the default value Klarna uses when this setting is not explicitly provided? If not, we should probably set it to `['person', 'organization']` to prevent adverse effects on existing implementations.

2020-09-14 18:13 UTC, jannejava commented
Great! Yes, `person` is the default value if nothing is set.

2020-09-16 06:04 UTC, fred-jan commented
> Great! Yes, person is the default value if nothing is set.

Superb, I'll merge once the unit test changes have been added :+1:

2020-11-11 13:22 UTC, fred-jan commented
@jannejava Could you apply the changes I pasted above into your branch? That way I'll be able to merge and close this PR.

2022-02-27 09:58 UTC, jannejava commented
@fred-jan Have forgotten this issue. Do you need something from me. Looks like applied the patches from your branch? Do you need something more from me?

2022-09-16 07:56 UTC, fred-jan commented
Hi @jannejava, I'm no longer working for the company maintaining this package. Sorry for my late reply nonetheless :disappointed:  @frankverhoeven or @LittlestFluffy, would you be able to take over this PR?

2024-03-01 13:02 UTC, fred-jan commented
This repository is no longer maintained. Please fork this repository if you would still like to have this change included.

2024-03-01 13:02 UTC, closed without merging